import {useEffect,useMemo,useRef,useState} from 'react';
import {useCatalog} from '../lib/catalog.jsx';
import {TERPENES} from '../data/engine-terpenes.js';
import {reviewPanel} from '../lib/coa-import.js';
import {extractReport,preparePhoto} from '../lib/extract-report.js';
import {classify,bandSegments,blendName} from '../lib/classifier.js';
import Fingerprint from '../components/Fingerprint.jsx';
export default function Import(){
 const [catalog,setProducts]=useCatalog();const [report,setReport]=useState(null),[page,setPage]=useState(0),[rows,setRows]=useState([]),[total,setTotal]=useState(''),[name,setName]=useState(''),[farm,setFarm]=useState(''),[batch,setBatch]=useState(''),[thc,setThc]=useState(''),[copy,setCopy]=useState(''),[photo,setPhoto]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState(null),[fileName,setFileName]=useState(''),[sourceURL,setSourceURL]=useState('');const controller=useRef(null);
 useEffect(()=>()=>controller.current?.abort(),[]);useEffect(()=>()=>{if(sourceURL)URL.revokeObjectURL(sourceURL)},[sourceURL]);
 const audit=useMemo(()=>reviewPanel(rows,total),[rows,total]);const result=useMemo(()=>classify(audit.values),[audit.values]);const band=result?bandSegments(result):[];
 function selectPage(data,index){const p=data.pages[index];setPage(index);setRows(p.rows);setTotal(p.total);setThc(p.thc);setConfirmed(false);setSaved(null);if(p.meta.product||p.meta.strain)setName(p.meta.product||p.meta.strain);if(p.meta.farm||p.meta.grower||p.meta.producer)setFarm(p.meta.farm||p.meta.grower||p.meta.producer);if(p.meta.batch||p.meta.lot)setBatch(p.meta.batch||p.meta.lot)}
 async function upload(file){if(!file)return;controller.current?.abort();const control=new AbortController();controller.current=control;setBusy(true);setError('');setSaved(null);setReport(null);setRows([]);setConfirmed(false);setFileName(file.name);setSourceURL(URL.createObjectURL(file));try{const data=await extractReport(file,setStatus,control.signal);setReport(data);selectPage(data,data.selected);setStatus('Extraction complete. Check the values against your report.')}catch(e){if(e.name!=='AbortError')setError(e.message);else setStatus('Reading cancelled. Choose another report when ready.')}finally{setBusy(false)}}
 function changeRow(i,field,value){setRows(rs=>rs.map((r,j)=>i===j?{...r,[field]:value}:r));setConfirmed(false);setSaved(null)}
 function save(){if(!confirmed||audit.issues.length||!name.trim())return;const id=saved||crypto.randomUUID();const product={id,category:'flower',name:name.trim(),grower:farm.trim()||'Farm not provided',tier:'Top Shelf',values:audit.values,thc:thc===''?null:Number(thc),blurb:copy.trim()||`${blendName(result)} aroma profile.`,photo,classificationSource:'Reviewed user report',provenance:{fileName,method:report.pages[page].method,page:page+1,reportedTotal:Number(total),modeledCoverage:audit.coverage,sourceRows:rows,reviewedAt:new Date().toISOString(),batch},manualTotalTerp:Number(total)};setProducts(ps=>ps.some(p=>p.id===id)?ps.map(p=>p.id===id?product:p):[...ps,product]);setSaved(id)}
 return <main className="production-tool import-tool"><div className="eyebrow">FARM → REVIEWED PANEL → YOUR ASSETS</div><h1>Your flower.<br/>Its own <em>fingerprint.</em></h1><p className="tool-intro">Upload a terpene report and an optional flower photo. Review the results once, then create social posts, a chemovar sales card, and aroma labels from the same panel. Files are read on this device.</p>
 <div className="workflow-steps"><span className="active">01 / Upload</span><span className={report?'active':''}>02 / Review</span><span className={saved?'active':''}>03 / Create & share</span></div>
 <div className="import-layout"><div><section className="production-panel"><h2>01 / Bring your results</h2><label className="upload-field">Terpene test report<input type="file" accept=".pdf,.csv,.png,.jpg,.jpeg,.webp" disabled={busy} onChange={e=>upload(e.target.files[0])}/></label><p className="fine-note">PDF, CSV, or a clear photograph / scan. Up to 25 MB and 20 PDF pages. CSV: analyte, result (% or mg/g), plus total terpenes.</p><a href="/assets/example-terpene-panel.csv" download>Download an example CSV ↓</a>{busy&&<button onClick={()=>controller.current?.abort()}>Cancel reading</button>}<p role="status">{status}</p>{error&&<p role="alert" className="error-note">{error}</p>}
 <label className="upload-field">Flower photograph (optional)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{if(!e.target.files[0])return;try{setPhoto(await preparePhoto(e.target.files[0]));setSaved(null);setError('')}catch(e){setError(e.message)}}}/></label>{photo&&<div className="photo-review"><img src={photo} alt="Your uploaded flower"/><button onClick={()=>{setPhoto('');setSaved(null)}}>Remove photo</button></div>}</section>
 <section className="production-panel settings-grid"><h2>Flower & farm</h2><label>Flower name<input maxLength="70" value={name} onChange={e=>{setName(e.target.value);setSaved(null)}} placeholder="e.g. Orchard Haze"/></label><label>Farm / producer<input maxLength="70" value={farm} onChange={e=>{setFarm(e.target.value);setSaved(null)}} placeholder="Your farm"/></label><label>Batch / lot<input maxLength="100" value={batch} onChange={e=>{setBatch(e.target.value);setSaved(null)}}/></label><label>Reported total THC % (optional)<input type="number" min="0" max="100" step="0.01" value={thc} onChange={e=>{setThc(e.target.value);setSaved(null)}}/></label><label>Your aroma description (optional)<textarea maxLength="220" rows="3" value={copy} onChange={e=>{setCopy(e.target.value);setSaved(null)}} placeholder="Describe what you actually smell."/></label></section></div>
 <section className="production-panel review-panel"><h2>02 / Review the panel</h2>{!report?<div className="empty-review"><Fingerprint ranked={[]} size={190}/><p>Your report becomes a fingerprint and proportional band here.</p><p className="fine-note">OCR can confuse letters, decimals, and columns. You approve the source values before anything is saved.</p></div>:<>
 <div className="action-row"><a href={sourceURL} target="_blank" rel="noreferrer">Open original report ↗</a><span>{report.pages[page].method}</span></div>{report.pages.length>1&&<label className="upload-field">Terpene report page<select value={page} onChange={e=>selectPage(report,Number(e.target.value))}>{report.pages.map((p,i)=><option key={i} value={i}>Page {i+1} · {p.rows.filter(r=>r.key).length} recognized rows</option>)}</select></label>}
 <p className="fine-note">Keep laboratory names and separate isomer rows. Assign a model compound only when supported by the report. Values below are percentages; mg/g is divided by 10. Uncheck non-terpene metadata or duplicate rows, keeping the source record.</p>
 <div className="review-table-wrap"><table className="review-table"><thead><tr><th>Use</th><th>Laboratory analyte</th><th>Model compound</th><th>Result %</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className={!r.included?'excluded':''}><td><input type="checkbox" aria-label={`Include ${r.raw||'row '+(i+1)}`} checked={r.included} onChange={e=>changeRow(i,'included',e.target.checked)}/></td><td><input aria-label={`Analyte ${i+1}`} value={r.raw} onChange={e=>changeRow(i,'raw',e.target.value)}/><small>{r.originalResult} {r.unit}{r.flag?` · ${r.flag}`:''}</small></td><td><select aria-label={`Model compound ${i+1}`} value={r.key} onChange={e=>changeRow(i,'key',e.target.value)}><option value="">Unmodeled / unknown</option>{TERPENES.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></td><td><input type="number" aria-label={`Result ${i+1}`} min="0" max="100" step="0.001" value={r.value} onChange={e=>changeRow(i,'value',e.target.value)}/></td></tr>)}</tbody></table></div><button onClick={()=>{setRows(rs=>[...rs,{raw:'',key:'',value:'',originalResult:'Added during review',unit:'%',included:true}]);setConfirmed(false);setSaved(null)}}>Add a missing row</button>
 <label className="upload-field total-field">Lab-reported total terpenes %<input type="number" min="0" max="100" step="0.001" value={total} onChange={e=>{setTotal(e.target.value);setConfirmed(false);setSaved(null)}}/></label><div className="review-metrics"><div><small>INCLUDED MASS</small><strong>{audit.sum.toFixed(3)}%</strong></div><div><small>MODELED COVERAGE</small><strong>{(audit.coverage*100).toFixed(1)}%</strong></div><div><small>UNMODELED MASS</small><strong>{audit.unmodeled.toFixed(3)}%</strong></div></div>
 {audit.issues.length>0&&<ul className="review-issues">{audit.issues.map(x=><li key={x}>{x}</li>)}</ul>}
 <details><summary>Extracted source text</summary><pre className="source-text">{report.pages[page].text}</pre></details>
 <label className="review-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the included compounds, result column, units, and total against the original report.</label>
 <button className="button primary" disabled={!confirmed||audit.issues.length>0||!name.trim()||busy||(thc!==''&&(!Number.isFinite(Number(thc))||Number(thc)<0||Number(thc)>100))} onClick={save}>Save reviewed flower & create assets →</button>
 </>}</section></div>
 {result&&report&&<section className="import-result production-panel"><div><div className="eyebrow">{saved?'03 / READY TO CREATE':'DRAFT / AWAITING REVIEW'}</div><h2>{name||'Your flower'}</h2><p>{blendName(result)} · {result.confidence}</p><div className="specimen-band">{band.map(b=><span key={b.key} style={{background:b.color,flex:b.frac}}>{b.short} {b.pct}%</span>)}</div><p className="fine-note">Band percentages are relative aroma model scores, not laboratory concentrations. The fingerprint represents {Math.round(audit.coverage*1000)/10}% of the included terpene mass.</p>{saved&&<div className="action-row"><a className="button primary" href={`#social?strain=${saved}`}>Open my social & chemovar assets ↗</a><a className="button" href={`#labels?product=${saved}`}>Preview my labels ↗</a><a className="button" href="#workflows?role=buyer">Find flower for a menu ↗</a><button className="button" onClick={()=>{const p=catalog.find(x=>x.id===saved),url=URL.createObjectURL(new Blob([JSON.stringify({schema:'flower-spectrum-reviewed-flower-v1',product:p},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='flower-spectrum-reviewed-flower.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download reviewed record JSON ↓</button></div>}</div><Fingerprint ranked={result.ranked} size={260}/></section>}
 </main>
}
