import PDFPreview from '../components/PDFPreview.jsx';
import {useState,useEffect,useMemo} from 'react';
import {useCatalog} from '../lib/catalog.jsx';
import {buildLabelPDF,labelOrder,TEMPLATES} from '../lib/labels.js';
export default function Labels(){
 const [catalog]=useCatalog();const products=useMemo(()=>catalog.filter(p=>p.category==='flower'),[catalog]);const requested=new URLSearchParams(location.hash.split('?')[1]).get('product');const [selected,setSelected]=useState(()=>requested&&products.some(p=>p.id===requested)?[requested]:products.filter(p=>p.sourceId).map(p=>p.id));const [copies,setCopies]=useState(1),[order,setOrder]=useState('grouped'),[offset,setOffset]=useState(0),[cutGuides,setCut]=useState(true),[url,setUrl]=useState(''),[blob,setBlob]=useState(null),[error,setError]=useState('');
 const chosen=products.filter(p=>selected.includes(p.id));let count=0;try{count=labelOrder(chosen,copies,order).length}catch{}
 useEffect(()=>{setUrl('');setBlob(null);setError('');if(!selected.length)return;const timer=setTimeout(generate,250);return()=>clearTimeout(timer)},[products,selected,copies,order,offset,cutGuides]);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 function generate(){try{const doc=buildLabelPDF(chosen,{copies,order,offset,cutGuides});const next=doc.output('blob');setBlob(next);setUrl(URL.createObjectURL(next));setError('')}catch(e){setError(e.message)}}
 return <main className="production-tool"><div className="eyebrow">FROM THE SHARED CATALOG / TRUE PDF EXPORT</div><h1>A small label.<br/>A complete <em>aroma story.</em></h1><p className="tool-intro">Avery 6464 · 4 × 3⅓ inches · six labels per US Letter sheet. Print at 100% / Actual size, with scaling disabled. Test alignment on plain paper before using label stock.</p><div className="label-layout"><div><section className="production-panel"><h2>Choose your flower</h2><div className="action-row"><button onClick={()=>setSelected(products.map(p=>p.id))}>All</button><button onClick={()=>setSelected([])}>None</button><button onClick={()=>setSelected(products.filter(p=>p.sourceId).map(p=>p.id))}>Historical samples</button></div><div className="label-products">{products.map(p=><label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,p.id]:prev.filter(id=>id!==p.id))}/><span><strong>{p.name}</strong><small>{p.category} · {p.provenance?.reviewedAt?'Reviewed report':p.sourceId?'Historical sample':p.classificationSource?'User-entered panel':'Illustrative catalog'}</small></span></label>)}</div><a href="#import">Upload a flower report ↗</a></section><section className="production-panel settings-grid"><label>Label stock<select value="avery6464" readOnly>{Object.values(TEMPLATES).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Copies per product<input type="number" min="1" max="200" value={copies} onChange={e=>setCopies(Number(e.target.value))}/></label><label>Copy order<select value={order} onChange={e=>setOrder(e.target.value)}><option value="grouped">Group copies</option><option value="interleaved">Interleave products</option></select></label><label>Start at label<select value={offset} onChange={e=>setOffset(Number(e.target.value))}>{Array.from({length:6},(_,i)=><option key={i} value={i}>{i+1}{i===0?' · full sheet':''}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={cutGuides} onChange={e=>setCut(e.target.checked)}/>Show cut guides</label><p>{chosen.length} products · {count} labels · {count?Math.ceil((count+offset)/6):0} pages</p><button className="button primary" onClick={generate} disabled={!chosen.length}>Refresh label preview</button>{url&&<a className="button" href={url} download="flower-spectrum-labels.pdf">Download PDF ↓</a>}{error&&<p role="alert">{error}</p>}</section><p className="fine-note">Aroma merchandising labels. Add and review any required retail package disclosures separately. Historical panels and illustrative products are identified on each label.</p></div><div className="label-preview">{blob?<PDFPreview blob={blob}/>:<div><span className="eyebrow">THE FINAL SHEET</span><h2>Ready when you are.</h2><p>Choose flower to see your label sheet.<br/>The preview updates as you adjust the settings.</p></div>}</div></div></main>
}
