import {useMemo,useState} from 'react';
import {useCatalog} from '../lib/catalog.jsx';
import {PROFILES} from '../data/profiles.js';
import {TERPENES} from '../data/engine-terpenes.js';
import {productClassification,productValues} from '../lib/product-model.js';
import {bandSegments} from '../lib/classifier.js';
import Fingerprint from '../components/Fingerprint.jsx';
const paths={farm:[['Bring a batch','Upload the flower photograph and its terpene PDF, CSV, or scan. Keep a separate record for each tested batch.','#import','Upload a report'],['Review its signature','Check the report’s compounds, units, and total. Save the reviewed panel to your local flower catalog.','#import','Review a panel'],['Tell its story','Choose your flower in Social studio. Export a strain highlight, story, fingerprint ID, and chemovar sales card to send to a buyer.','#social','Open Social studio']],buyer:[['Describe the menu gap','Choose an aroma profile or a specific terpene below. For example, find citrus-led flower with at least 0.30% limonene.','#finder','Search the catalog'],['Compare candidate batches','Read the ten-sector fingerprints and source labels. Shortlist the flower you want to investigate. Check the original report before a purchase.','#finder','Build a shortlist'],['Build the flower menu','Send the shortlist to Print menu, enter your actual retail pricing, then download labels or browse the digital flower menu.','#print','Open Print menu']],staff:[['Start with a preference','Ask about aroma: citrus, earth, pine, spice, or floral. Use the profile reference to explain the common vocabulary.','#profiles','Read the profiles'],['Explore the flower','Use the digital menu’s aroma filters and product details. The band and fingerprint connect the shelf to the flower’s panel.','#menu','Open the flower menu'],['Keep the shelf consistent','Print the same flower’s aroma label, then use the education library for short explanations.','#labels','Preview labels']]};
export default function Workflows(){
 const q=new URLSearchParams(location.hash.split('?')[1]);const [role,setRole]=useState(['farm','buyer','staff'].includes(q.get('role'))?q.get('role'):'farm');const [products]=useCatalog();const [profile,setProfile]=useState(PROFILES.some(p=>p.key===q.get('profile'))?q.get('profile'):'citrus_bright'),[compound,setCompound]=useState(''),[minimum,setMinimum]=useState('0'),[reviewedOnly,setReviewed]=useState(false),[shortlist,setShortlist]=useState([]);
 const results=useMemo(()=>products.filter(p=>p.category==='flower').map(p=>({...p,c:productClassification(p)})).filter(p=>p.c&&(!reviewedOnly||p.provenance?.reviewedAt)&&(!compound||(Number(productValues(p)[compound])||0)>=Number(minimum))).map(p=>({...p,score:p.c.ranked.find(r=>r.key===profile)?.pct||0})).filter(p=>!profile||p.score>0).sort((a,b)=>b.score-a.score),[products,profile,compound,minimum,reviewedOnly]);
 const chosen=products.filter(p=>shortlist.includes(p.id));const ids=encodeURIComponent(chosen.map(p=>p.id).join(','));
 function download(){const cell=x=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const csv=[['Flower','Farm','Batch','Source','Profile','Relative aroma score %','Reported total terpenes %'],...chosen.map(p=>{const c=productClassification(p);return [p.name,p.grower,p.provenance?.batch||'',p.provenance?.reviewedAt?'Reviewed user report':p.sourceId?'Historical sample':'Illustrative / manual',PROFILES.find(x=>x.key===profile)?.label||'',c?.ranked.find(x=>x.key===profile)?.pct||0,p.provenance?.reportedTotal??c?.totalTerp??'']})].map(row=>row.map(cell).join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='flower-spectrum-buyer-shortlist.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 return <main className="production-tool"><div className="eyebrow">REAL PEOPLE / ONE CONNECTED FLOWER SYSTEM</div><h1>From a farm’s batch<br/>to a buyer’s <em>menu.</em></h1><p className="tool-intro">Follow the same flower through the system. A farm turns test results into a useful sales story. A buyer looks for the aroma their menu is missing. Staff help customers recognize that flower on the shelf.</p><div className="persona-tabs" role="tablist" aria-label="Choose your role">{[['farm','I grow flower'],['buyer','I buy flower'],['staff','I help customers']].map(([id,label])=><button role="tab" aria-selected={role===id} key={id} onClick={()=>setRole(id)}>{label}</button>)}</div>
 <div className="journey-cards">{paths[role].map(([title,body,href,cta],i)=><article key={title}><span className="eyebrow">0{i+1}</span><h2>{title}</h2><p>{body}</p><a href={href==='#finder'?'#workflows?role=buyer':href} onClick={href==='#finder'?e=>{e.preventDefault();document.getElementById('finder')?.scrollIntoView({behavior:'smooth'})}:undefined}>{cta} →</a></article>)}</div>
 {role==='farm'&&<section className="workflow-example"><div><div className="eyebrow">EXAMPLE / THE CULTIVATOR’S HANDOFF</div><h2>One batch. A coordinated kit.</h2><p>“I have a fresh batch to introduce to retailers.”</p><p>Upload its lab panel and photograph, confirm the extracted values, then export the fingerprint-led social post and chemovar sales card. The buyer receives a clear aroma signature and the original report alongside it.</p><a className="button primary" href="#import">Start with my flower →</a></div><div className="deliverable-stack"><span>TERPENE REPORT + FLOWER PHOTO</span><b>↓</b><strong>Reviewed batch fingerprint</strong><b>↓</b><span>Social post · Story · Chemovar card · Label</span></div></section>}
 {role==='buyer'&&<section id="finder" className="buyer-finder"><div className="section-heading"><div><div className="eyebrow">TRY THE WORKFLOW / FLOWER FINDER</div><h2>Find the aroma your menu needs.</h2></div><p>Search this device’s catalog. Results are aroma-model matches, not live supplier inventory.</p></div><div className="finder-controls production-panel"><label>Aroma profile<select aria-label="Aroma profile" value={profile} onChange={e=>setProfile(e.target.value)}>{PROFILES.map(p=><option key={p.key} value={p.key}>{p.label}</option>)}</select></label><label>Specific terpene (optional)<select aria-label="Specific terpene (optional)" value={compound} onChange={e=>setCompound(e.target.value)}><option value="">Any compound</option>{TERPENES.map(t=><option value={t.key} key={t.key}>{t.label}</option>)}</select></label><label>Minimum terpene %<input type="number" min="0" max="100" step="0.01" disabled={!compound} value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><label className="check-label"><input type="checkbox" checked={reviewedOnly} onChange={e=>setReviewed(e.target.checked)}/>Reviewed uploads only</label></div><p className="fine-note">Ranked by relative aroma score for the selected profile. Specific-terpene filters require numerical panel values; manually assigned profiles alone do not provide measured concentrations. Seed catalog products are demonstrations.</p>
 <div className="shortlist-bar"><strong>{chosen.length} flower shortlisted</strong><button disabled={!chosen.length} onClick={download}>Export shortlist CSV ↓</button><a aria-disabled={!chosen.length} className="button" href={chosen.length?`#print?ids=${ids}`:undefined}>Build this print menu →</a><a href="#import">Add a supplier’s report ↗</a></div>
 <div className="buyer-results">{results.map(p=><article key={p.id}><div className="candidate-top"><div><small>{p.provenance?.reviewedAt?'REVIEWED UPLOAD':p.sourceId?'HISTORICAL SAMPLE':'ILLUSTRATIVE / MANUAL'}</small><h3>{p.name}</h3><p>{p.grower}</p></div><Fingerprint ranked={p.c.ranked} size={110}/></div><div className="specimen-band">{bandSegments(p.c).map(b=><span key={b.key} style={{background:b.color,flex:b.frac}}>{b.short} {b.pct}%</span>)}</div><p>{p.score}% relative {PROFILES.find(x=>x.key===profile)?.short.toLowerCase()} score{compound?` · ${Number(productValues(p)[compound]||0).toFixed(2)}% ${TERPENES.find(x=>x.key===compound)?.label}`:''}</p><p className="fine-note">{p.provenance?`Batch ${p.provenance.batch||'not supplied'} · ${p.provenance.fileName}`:p.sourceId?'Historical source panel. Availability and pricing are illustrative.':'Demonstration product. Verify with a supplier’s test report.'}</p><div className="action-row"><button aria-pressed={shortlist.includes(p.id)} onClick={()=>setShortlist(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])}>{shortlist.includes(p.id)?'Remove from shortlist':'Shortlist flower'}</button>{Object.keys(productValues(p)).length>0&&<a href={`#social?strain=${p.classificationSource?p.id:p.sourceId||p.id}`}>View chemovar & social assets ↗</a>}</div></article>)}</div>{!results.length&&<p className="production-panel">No matching flower in this local catalog. Change the filters or <a href="#import">upload a supplier’s report</a>.</p>}
 </section>}
 {role==='staff'&&<section className="workflow-example"><div><div className="eyebrow">EXAMPLE / AT THE COUNTER</div><h2>“Something bright and citrusy.”</h2><p>Open the citrus flower view, compare the aroma descriptions, and use the fingerprint to explain how two flowers differ. The matching shelf label keeps that conversation visible after the screen is closed.</p><a className="button primary" href="#menu?profile=citrus_bright">Explore citrus flower →</a></div><div className="deliverable-stack"><span>CUSTOMER PREFERENCE</span><b>↓</b><strong>Aroma-first flower menu</strong><b>↓</b><span>Product details · Education · Shelf label</span></div></section>}
 <p className="fine-note">This is a local workflow demonstration: no supplier marketplace, ordering, shared cloud catalog, or POS connection is implied. Share exported files and the original report with your buyer; uploads remain in your browser.</p></main>
}
