import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import vm from 'node:vm';
import {PROFILES} from '../src/data/profiles.js';
import {STRAINS} from '../src/data/strains.js';
import {DEFAULT_PRODUCTS} from '../src/data/products.js';
import {classify,bandSegments} from '../src/lib/classifier.js';
import {csvSerialize,csvParse,productToRow,parseCsvToProducts,CSV_MASTER,getBand,activeSales} from '../src/lib/menu-data.js';
test('supplied originals remain byte-for-byte intact',()=>{const manifest=JSON.parse(readFileSync(new URL('../source/manifest.json',import.meta.url)));for(const x of manifest){const file=readFileSync(new URL('../source/'+x.file,import.meta.url));assert.equal(createHash('sha256').update(file).digest('hex'),x.sha256);assert.equal(file.length,x.bytes)}});
test('shared profile keys, colors, and order match all three originals',()=>{assert.equal(PROFILES.length,10);for(const file of ['tablet-menu.jsx','education-materials.jsx','cultivator-social-kit.html']){const s=readFileSync(new URL('../source/'+file,import.meta.url),'utf8');for(const p of PROFILES){assert.ok(s.includes(p.key));assert.ok(s.includes(p.color))}}});
test('classification matches the supplied social engine for every historical panel',()=>{const source=readFileSync(new URL('../source/cultivator-social-kit.html',import.meta.url),'utf8');const code=source.slice(source.indexOf('const PROFILES=['),source.indexOf('/* ═══════════════ STRIP'));const context=vm.createContext({});vm.runInContext(code,context);for(const s of STRAINS){context.values=s.values;const legacy=JSON.parse(vm.runInContext('JSON.stringify(classify(values))',context));const modern=classify(s.values);assert.deepEqual(modern.ranked.map(x=>({key:x.key,pct:x.pct})),legacy.ranked.map(x=>({key:x.key,pct:x.pct})));assert.equal(modern.confidence,legacy.confidence);assert.equal(modern.totalTerp,legacy.totalTerp)}});
test('empty panels return no result; unsupported analytes are not scored',()=>{assert.equal(classify({}),null);assert.deepEqual(classify({myrcene:1,anisole:99}),classify({myrcene:1}))});
test('menu and social samples share all band segments',()=>{for(const s of STRAINS){const p=DEFAULT_PRODUCTS.find(x=>x.id===s.id);assert.deepEqual(getBand(p),bandSegments(s.c).map(x=>({key:x.key,pct:x.pct})))}});
test('CSV survives quoted commas, quotes, CRLF and multiline text',()=>{const s=csvSerialize(['Name','Blurb'],[{Name:'A, "B"',Blurb:'Line 1\nLine 2'}]);assert.deepEqual(csvParse(s.replaceAll('\n','\r\n')),[['Name','Blurb'],['A, "B"','Line 1\nLine 2']])});
test('complete catalog round trip retains IDs, flavor, source, and all exported fields',()=>{const serialized=csvSerialize(CSV_MASTER,DEFAULT_PRODUCTS.map(productToRow));const result=parseCsvToProducts(serialized);assert.deepEqual(result.errors,[]);assert.equal(result.products.length,DEFAULT_PRODUCTS.length);assert.equal(csvSerialize(CSV_MASTER,result.products.map(productToRow)),serialized)});
test('invalid imports produce actionable errors',()=>{for(const text of ['Wrong,Header\na,b','Category,Name\nunknown,Bad','Category,Name,SalePct\nflower,Bad,101','Category,Name,Price1g\nflower,Bad,-1','Category,Name,PrimaryProfile\nflower,Bad,unknown','Category,Name\nflower,"open','ID,Category,Name\na,flower,One\na,flower,Two'])assert.ok(parseCsvToProducts(text).errors.length,text)});
test('sample sale countdown expires exactly at its deadline',()=>{const sample={salePct:20,saleEndsMin:1};assert.equal(activeSales([sample],59).length,1);assert.equal(activeSales([sample],60).length,0)});
