import test from 'node:test';
import assert from 'node:assert/strict';
import {parsePanel,reviewPanel,csvRows} from '../src/lib/coa-import.js';
import {socialStrains} from '../src/lib/social-catalog.js';
test('CSV uses explicit result column rather than LOD, preserves quoted names and source units',()=>{const p=parsePanel('Analyte,LOD,Result (mg/g)\n"1,8-Cineole",0.01,2\nBeta-Myrcene,0.02,8\nTotal Terpenes,0,10',{csv:true});assert.equal(p.rows[0].raw,'1,8-Cineole');assert.equal(p.rows[0].key,'eucalyptol');assert.equal(p.rows[0].value,.2);assert.equal(p.total,1);assert.deepEqual(reviewPanel(p.rows,p.total).issues,[])});
test('missing result is blocked without falling back to detection limit',()=>{const p=parsePanel('Analyte,LOD,Result (%)\nMyrcene,0.01,\nLimonene,0.02,0.5\nTotal Terpenes,,1',{csv:true});assert.equal(p.rows[0].value,'');assert.ok(reviewPanel(p.rows,p.total).issues.length)});
test('unmodeled source rows and isomers survive review; coverage gate blocks omitted mass',()=>{const p=parsePanel('Analyte,Result (%)\ncis-nerolidol,0.2\ntrans-nerolidol,0.1\nLimonene,0.3\ntrans-Phytol,0.4\nTotal Terpenes,1',{csv:true});assert.equal(p.rows.length,4);const r=reviewPanel(p.rows,p.total);assert.ok(Math.abs(r.values.nerolidol-.3)<1e-10);assert.ok(Math.abs(r.unmodeled-.4)<1e-10);assert.ok(r.issues.some(x=>x.includes('95%')));assert.equal(p.rows[3].key,'')});
test('nondetect rows are preserved as zero; invalid and negative results block export',()=>{const p=parsePanel('Analyte,Result (%)\nMyrcene,<0.01\nLimonene,0.5\nLinalool,-0.1\nTotal Terpenes,0.4',{csv:true});assert.equal(p.rows[0].value,0);assert.ok(p.rows[0].flag);assert.ok(reviewPanel(p.rows,p.total).issues.some(x=>x.includes('Linalool')))});
test('aligned PDF text parses report totals and converts units',()=>{const p=parsePanel('Product: QA Flower\nAnalyte\tResult (%)\tResult (mg/g)\nMyrcene\t0.65\t6.5\nLimonene\t0.42\t4.2\nTotal Terpenes\t1.07\t10.7');assert.equal(p.meta.product,'QA Flower');assert.deepEqual(reviewPanel(p.rows,p.total).issues,[])});
test('OCR single result lines require a reconciled total and preserve all source text',()=>{const p=parsePanel('Myrcene 0.65 %\nLimonene 0.42 %\nTotal Terpenes 1.07 %');assert.equal(p.rows.length,2);assert.equal(p.total,1.07);assert.deepEqual(reviewPanel(p.rows,p.total).issues,[]);assert.ok(reviewPanel(p.rows,1.2).issues.length)});
test('CSV malformed quotes reject rather than losing rows',()=>assert.throws(()=>csvRows('Analyte,Result\n"Limonene,.5'),/unclosed/));
test('reviewed import reaches social assets with its own source names and no invented cannabinoids',()=>{const p=parsePanel('Analyte,Result (%)\nMyrcene,0.6\nLimonene,0.4\nTotal Terpenes,1',{csv:true});const r=reviewPanel(p.rows,p.total);const s=socialStrains([{id:'qa',category:'flower',name:'QA Flower',grower:'QA Farm',values:r.values,provenance:{reviewedAt:'2026-09-27',sourceRows:p.rows,reportedTotal:1,modeledCoverage:1,method:'CSV',fileName:'qa.csv',page:1}}]).at(-1);assert.equal(s.name,'QA Flower');assert.equal(s.terps,'1.00');assert.equal(s.thc,'—');assert.equal(s.panel[0][0],'Myrcene');assert.ok(s.c.ranked.length===10)});
test('multiline Mass headers select percent ahead of mg/g and LOQ',()=>{const p=parsePanel('Terpenes\nAnalyte\tMass\tMass\tLOQ\n%\tmg/g\t%\nMyrcene\t0.6\t6\t0.02\nLimonene\t0.4\t4\t0.02\n1.00%\nTotal Terpenes\nMethod: laboratory');assert.equal(p.total,1);assert.equal(p.rows.length,2);assert.deepEqual(reviewPanel(p.rows,p.total).issues,[])});

test('editing reviewed panel values invalidates the review and social assets use current concentrations',()=>{const p=parsePanel('Analyte,Result (%)\nMyrcene,0.6\nLimonene,0.4\nTotal Terpenes,1',{csv:true});const s=socialStrains([{id:'edited',name:'Edited flower',category:'flower',values:{myrcene:.2,limonene:.8},provenance:{reviewedAt:'2026-09-27',sourceRows:p.rows,reportedTotal:1,modeledCoverage:1,method:'CSV',fileName:'original.csv',page:1}}]).at(-1);assert.ok(s.sourceNote.includes('User-entered'));assert.equal(s.panel.find(r=>r[0]==='Myrcene')[1],.2);assert.ok(!s.copy[0].startsWith('Reviewed'))});
