import {useState} from 'react';
import {useCatalog} from '../lib/catalog.jsx';
import {withClassification,productValues} from '../lib/product-model.js';
import {ENGINE_TERPENES} from '../lib/classifier.js';
export default function CatalogBridge({name,producer,values,result,mode,setName,setProducer,setValues,setMode}) {
 const [products,setProducts]=useCatalog();const [target,setTarget]=useState('');const [status,setStatus]=useState('');
 const unknown=Object.keys(values).filter(k=>values[k]>0&&!ENGINE_TERPENES.some(t=>t.key===k));
 const total=Object.values(values).reduce((s,v)=>s+(Number(v)||0),0);const valid=result&&total<=100&&name.trim();
 function load(id){setTarget(id);setStatus('');const p=products.find(x=>x.id===id);if(p){setName(p.name);setProducer(p.grower||'');setValues({...productValues(p)});setMode(p.category==='concentrate'?'live_resin':'flower')}}
 function save(){const id=target||crypto.randomUUID();const existing=products.find(p=>p.id===id);const p=withClassification({...existing,id,name:name.trim(),grower:producer,category:existing?.category||(mode==='flower'?'flower':'concentrate'),values:{...values},classificationSource:'User-entered panel; laboratory report not independently verified',illustrative:existing?.illustrative??true,blurb:existing?.blurb||'Aroma modeled from entered terpene values.',featured:existing?.featured??true});setProducts(prev=>existing?prev.map(x=>x.id===id?p:x):[p,...prev]);setTarget(id);setStatus(`${p.name} saved to the shared catalog.`)}
 return <section className="catalog-bridge"><div><strong>Classify → catalog → digital, print & labels</strong><p>Load a product to update its panel, or save your current panel as a new product. Prices and potency remain editable in the menu catalog.</p></div><div className="bridge-controls"><label>Catalog product<select value={target} onChange={e=>load(e.target.value)}><option value="">New product</option>{products.filter(p=>p.category!=='edible').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="button primary" disabled={!valid} onClick={save}>{target?'Update catalog product':'Save to catalog'}</button><a href={result?`#menu?profile=${result.ranked[0].key}`:"#menu"}>Digital menu ↗</a><a href="#print">Print menu ↗</a><a href="#labels">Labels ↗</a></div>{unknown.length>0&&<p role="status">Unmodeled entries retained: {unknown.join(', ')}. Modeled total: {result?.totalRaw.toFixed(3)||0}% of {total.toFixed(3)}% entered.</p>}{total>100&&<p role="alert">Total terpene concentration cannot exceed 100%.</p>}{status&&<p role="status">{status}</p>}</section>
}
