async(page)=>{
 const root='https://flower-spectrum-suite.vercel.app/';const report={errors:[],externalRequests:[],checks:[]};page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(root))report.externalRequests.push(r.url())});await page.setViewportSize({width:1440,height:1000});await page.goto(root+'#import');await page.getByLabel('Terpene test report',{exact:true}).setInputFiles('public/assets/example-terpene-panel.csv');await page.getByText('Extraction complete.',{exact:false}).waitFor();await page.getByLabel('Flower name',{exact:true}).fill('Release verification flower');await page.getByLabel('Farm / producer').fill('Synthetic test farm');await page.getByLabel('I checked the included compounds',{exact:false}).check();await page.getByRole('button',{name:'Save reviewed flower & create assets →'}).click();await page.getByRole('link',{name:'Open my social & chemovar assets ↗'}).waitFor();const social=await page.getByRole('link',{name:'Open my social & chemovar assets ↗'}).getAttribute('href'),labels=await page.getByRole('link',{name:'Preview my labels ↗'}).getAttribute('href');report.checks.push({csvRows:await page.locator('.review-table tbody tr').count(),total:await page.getByLabel('Lab-reported total terpenes %').inputValue()});await page.setViewportSize({width:320,height:900});report.checks.push({filledImportMobileOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)});
 await page.setViewportSize({width:1440,height:1000});await page.goto(root+social);const frame=page.frameLocator('iframe');await frame.locator('#gallery .asset').first().waitFor();report.checks.push({socialName:await frame.locator('#selStrain option:checked').innerText()});const png=page.waitForEvent('download');await frame.getByRole('button',{name:'Export PNG',exact:true}).first().click();await(await png).saveAs('output/playwright/live-v3-highlight.png');
 await page.goto(root+labels);await page.locator('.clean-pdf canvas').waitFor();await page.waitForFunction(()=>document.querySelector('.clean-pdf canvas')?.width>500);await page.waitForTimeout(300);report.checks.push({cleanLabels:true,iframes:await page.locator('.label-preview iframe').count()});await page.screenshot({path:'output/playwright/live-v3-labels.png'});
 for(const file of ['terpenes-text.pdf','synthetic-scan.png','synthetic-scanned.pdf']){await page.goto(root+'#overview');await page.goto(root+'#import');await page.getByLabel('Terpene test report',{exact:true}).setInputFiles('output/playwright/fixtures/'+file);await page.getByText('Extraction complete.',{exact:false}).waitFor({timeout:60000});const total=await page.getByLabel('Lab-reported total terpenes %').inputValue();const rows=await page.locator('.review-table tbody tr').count();if(total!=='1.6'||rows!==5)throw Error('Unexpected live extraction: '+file);report.checks.push({file,rows,total})}
 await page.goto(root+'#workflows?role=buyer');await page.getByLabel('Specific terpene (optional)').selectOption('limonene');await page.getByLabel('Minimum terpene %').fill('0.30');report.checks.push({buyerMatches:await page.locator('.buyer-results article').count()});await page.getByRole('button',{name:'Shortlist flower',exact:true}).first().click();await page.getByRole('link',{name:'Build this print menu →'}).click();await page.locator('.print-pages .fs-row').first().waitFor();report.checks.push({shortlistPrintRows:await page.locator('.print-pages .fs-row').count()});
 await page.goto(root+'#profiles');await page.locator('.fingerprint-library article').first().waitFor();report.checks.push({fingerprintReferenceCards:await page.locator('.fingerprint-library article').count()});
 await page.goto(root+'#menu?profile=citrus_bright');await page.locator('.menu-layout').waitFor();report.checks.push({flowerOnlyNavigation:!(await page.getByRole('button',{name:/^(Edibles|Vapes|Concentrates|Pre-Rolls)$/}).count())});await page.evaluate(()=>{const a=JSON.parse(localStorage.getItem('fs-suite-catalog-v1'));localStorage.setItem('fs-suite-catalog-v1',JSON.stringify(a.filter(p=>p.name!=='Release verification flower')))});await page.goto(root+'#workflows');await page.reload();if(report.errors.length||report.checks.some(c=>c.filledImportMobileOverflow))throw Error(JSON.stringify(report));return report;
}
