from pathlib import Path
import base64
root=Path(__file__).resolve().parents[1]
def img(name):
 p=root/'documentation/assets'/name
 if name=='overview-desktop.png':p=root/'public/assets/portfolio-cover.png'
 return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><link rel="icon" href="data:,"><title>Flower Spectrum Suite — Portfolio Case Study</title><style>
*{box-sizing:border-box}body{margin:0;background:#0e0e0c;color:#e8e3d9;font-family:Arial,sans-serif}section{width:1120px;height:792px;padding:58px 68px;position:relative;overflow:hidden;page-break-after:always}section:last-child{page-break-after:auto}.eyebrow{font:11px monospace;letter-spacing:2px;color:#6aafa0}h1,h2,h3{font-family:Georgia,serif;font-weight:400}h1{font-size:67px;line-height:1.02;letter-spacing:-2px;margin:32px 0 22px}h2{font-size:43px;line-height:1.13;margin:20px 0}h3{font-size:24px;margin:12px 0}em{color:#6aafa0}p{font-size:14px;line-height:1.75;color:#bbb3a5}.intro{font-size:18px;max-width:730px}.rule{display:flex;height:9px;margin:28px 0}.rule i{flex:1}.cover-grid{display:grid;grid-template-columns:1fr 1fr;gap:35px}.cover-grid img{width:100%;border:1px solid #3a372f;margin-top:26px}.stats{display:flex;gap:35px;margin-top:30px}.stats b{display:block;font:36px Georgia,serif;color:#e8e3d9}.stats span{font:10px monospace;color:#aaa294;display:block;margin-top:10px;letter-spacing:1px}.foot{position:absolute;bottom:30px;left:68px;right:68px;display:flex;justify-content:space-between;font:10px monospace;letter-spacing:1px;color:#a8a092;border-top:1px solid #333129;padding-top:17px}.columns{display:grid;grid-template-columns:repeat(3,1fr);gap:30px;margin-top:25px}.columns article{border-top:3px solid #6aafa0;padding-top:20px}.shot{width:100%;border:1px solid #353329}.duo{display:grid;grid-template-columns:1.2fr 1fr;gap:30px;margin-top:25px}.duo img{width:100%}.caption{font:10px/1.6 monospace;letter-spacing:.4px;color:#a8a092;margin-top:12px}.paper{background:#f4eee3;color:#1a1816}.paper p{color:#62594e}.paper .eyebrow{color:#3d7468}.paper .foot{color:#62594e;border-color:#c8bead}.paper em{color:#3d7468}.paper .columns article{border-color:#9e6b4a}.note{padding:22px;background:#1c211b;border-left:3px solid #6aafa0;margin-top:22px}a{color:#6aafa0;text-decoration:none}li{color:#bbb3a5;font-size:14px;line-height:1.9}@page{size:1120px 792px;margin:0}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style></head><body>'''
colors=['#C9A84C','#6B8E5A','#D4A843','#B75F4A','#B98BBE','#D6B58A','#9E6B4A','#4F7A5B','#7FA688','#D28B49']
rule='<div class="rule">'+''.join(f'<i style="background:{c}"></i>' for c in colors)+'</div>'
def footer(n):return f'<div class="foot"><span>FLOWER SPECTRUM SUITE / CANNACRE8IVE</span><span>PORTFOLIO CASE STUDY / 0{n}</span></div>'
html+=f'''<section><div class="eyebrow">PRODUCT DESIGN / BRAND SYSTEM / FRONTEND DEVELOPMENT</div><h1>A language for<br/>what you <em>smell.</em></h1><p class="intro">A classifier, digital and print menus, labels, education, and creative studio. A report-to-asset workflow built around the fingerprint ID and proportional aroma band.</p>{rule}<div class="cover-grid"><div><h3>Flower Spectrum Suite</h3><p>A functional portfolio demonstration exploring how a shared visual vocabulary can carry a product story across discovery, learning, and creative output.</p><div class="stats"><div><b>10</b><span>AROMA PROFILES</span></div><div><b>6</b><span>CONNECTED TOOLS</span></div><div><b>1</b><span>SHARED SYSTEM</span></div></div></div><img src="{img('overview-desktop.png')}" alt="Real application overview"/></div>{footer(1)}</section>'''
html+=f'''<section class="paper"><div class="eyebrow">01 / THE DESIGN PROBLEM</div><h2>A consistent identity across<br/><em>different kinds of work.</em></h2><p class="intro">A retail menu, a teaching sheet, and a social post serve different audiences. They still need to tell a coherent story.</p><div class="columns"><article><div class="eyebrow">DISCOVER</div><h3>Retail experience</h3><p>A buyer searches the local flower catalog by aroma and specific terpene concentration, compares fingerprints, and sends a shortlist to a print menu.</p></article><article><div class="eyebrow">UNDERSTAND</div><h3>Classifier + education</h3><p>A farm uploads a PDF, CSV, or scanned terpene report and flower photo. Editable source rows, unit checks, total reconciliation, and human review precede classification.</p></article><article><div class="eyebrow">EXPRESS</div><h3>Labels + creative</h3><p>The reviewed flower generates social posts, a chemovar sales card, and six-up labels with a clean preview. Every output carries the fingerprint and band.</p></article></div>{rule}<h3>The integration decision</h3><p>Preserve the original source and working behavior. Extract shared profile identities, sample panels, and classification math. Add a clear suite navigation, connected handoffs, local persistence, and a presentation layer that makes the system easy to explore.</p><p class="caption">Sources: digital menu, education, social, classifier, print menu, labels; wholesale portal preserved as reference.</p>{footer(2)}</section>'''
html+=f'''<section><div class="eyebrow">02 / THE WORKING EXPERIENCE</div><h2>One source of identity.<br/><em>Multiple useful expressions.</em></h2><div class="duo"><div><img class="shot" src="{img('print-desktop.png')}" alt="Retail interface"/><p class="caption">PRINT / Measured pages from the same catalog used by the digital menu.</p></div><div><img class="shot" src="{img('workflows-buyer.png')}" alt="Social creative studio"/><p class="caption">BUY / Search aroma and terpene concentration, compare flower, shortlist, then print.</p><p>A farmer creates the identity; a buyer finds a menu fit; staff recognize the same flower on screen and on the shelf.</p></div></div>{footer(3)}</section>'''
html+=f'''<section><div class="eyebrow">03 / DELIVERY & SCOPE</div><h2>A project you can explore.<br/><em>Assets you can share.</em></h2><div class="columns"><article><h3>Interactive app</h3><p>Unified navigation, reusable data modules, shared browser catalog, PDF labels, measured print pagination, and full-panel CSV backup.</p></article><article><h3>Portfolio kit</h3><p>Real interface screenshots, native social PNGs, ten profile cards and SVG fingerprints, this case study, an editable HTML version, print primer, and sharing copy.</p></article><article><h3>Reviewable source</h3><p>Seven intact supplied files, a checksum manifest, architecture and design notes, roadmap, tests, and public repository.</p></article></div><div class="note"><h3>Evidence and boundaries</h3><p>This is a portfolio demonstration, with illustrative commercial data and historical sample panels supplied in the prototypes. New reports are processed locally and require source review. Historical samples retain their original provenance; no independent scientific review is implied. Educational copy needs editorial review before retail use. No live POS connection, production access control, or measured business uplift is claimed.</p></div><p style="margin-top:30px"><a href="https://flower-spectrum-suite.vercel.app">Explore: flower-spectrum-suite.vercel.app</a><br/><a href="https://github.com/cannacre8ive/flower-spectrum-suite">Source: github.com/cannacre8ive/flower-spectrum-suite</a></p>{footer(4)}</section></body></html>'''
(root/'portfolio/case-study.html').write_text(html)
print('Created editable four-page case study with embedded app screenshots.')
