from pathlib import Path
import base64
root=Path(__file__).resolve().parents[1]
def img(name):
 p=root/'documentation/assets'/name
 if name=='overview-desktop.png':p=root/'public/assets/portfolio-cover.png'
 return 'data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><link rel="icon" href="data:,"><title>Flower Spectrum Suite — Portfolio Case Study</title><style>
*{box-sizing:border-box}body{margin:0;background:#0e0e0c;color:#e8e3d9;font-family:Arial,sans-serif}section{width:1120px;height:792px;padding:58px 68px;position:relative;overflow:hidden;page-break-after:always}section:last-child{page-break-after:auto}.eyebrow{font:11px monospace;letter-spacing:2px;color:#6aafa0}h1,h2,h3{font-family:Georgia,serif;font-weight:400}h1{font-size:67px;line-height:1.02;letter-spacing:-2px;margin:32px 0 22px}h2{font-size:43px;line-height:1.13;margin:20px 0}h3{font-size:24px;margin:12px 0}em{color:#6aafa0}p{font-size:14px;line-height:1.75;color:#bbb3a5}.intro{font-size:18px;max-width:730px}.rule{display:flex;height:9px;margin:28px 0}.rule i{flex:1}.cover-grid{display:grid;grid-template-columns:1fr 1fr;gap:35px}.cover-grid img{width:100%;border:1px solid #3a372f;margin-top:26px}.stats{display:flex;gap:35px;margin-top:30px}.stats b{display:block;font:36px Georgia,serif;color:#e8e3d9}.stats span{font:10px monospace;color:#aaa294;display:block;margin-top:10px;letter-spacing:1px}.foot{position:absolute;bottom:30px;left:68px;right:68px;display:flex;justify-content:space-between;font:10px monospace;letter-spacing:1px;color:#a8a092;border-top:1px solid #333129;padding-top:17px}.columns{display:grid;grid-template-columns:repeat(3,1fr);gap:30px;margin-top:25px}.columns article{border-top:3px solid #6aafa0;padding-top:20px}.shot{width:100%;border:1px solid #353329}.duo{display:grid;grid-template-columns:1.2fr 1fr;gap:30px;margin-top:25px}.duo img{width:100%}.caption{font:10px/1.6 monospace;letter-spacing:.4px;color:#a8a092;margin-top:12px}.paper{background:#f4eee3;color:#1a1816}.paper p{color:#62594e}.paper .eyebrow{color:#3d7468}.paper .foot{color:#62594e;border-color:#c8bead}.paper em{color:#3d7468}.paper .columns article{border-color:#9e6b4a}.note{padding:22px;background:#1c211b;border-left:3px solid #6aafa0;margin-top:22px}a{color:#6aafa0;text-decoration:none}li{color:#bbb3a5;font-size:14px;line-height:1.9}@page{size:1120px 792px;margin:0}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style></head><body>'''
colors=['#C9A84C','#6B8E5A','#D4A843','#B75F4A','#B98BBE','#D6B58A','#9E6B4A','#4F7A5B','#7FA688','#D28B49']
rule='<div class="rule">'+''.join(f'<i style="background:{c}"></i>' for c in colors)+'</div>'
def footer(n):return f'<div class="foot"><span>FLOWER SPECTRUM SUITE / CANNACRE8IVE</span><span>PORTFOLIO CASE STUDY / 0{n}</span></div>'
html+=f'''<section><div class="eyebrow">PRODUCT DESIGN / BRAND SYSTEM / FRONTEND DEVELOPMENT</div><h1>A language for<br/>what you <em>smell.</em></h1><p class="intro">A connected retail menu, education library, and cultivator creative studio. Three prototypes brought together through one aroma system.</p>{rule}<div class="cover-grid"><div><h3>Flower Spectrum Suite</h3><p>A functional portfolio demonstration exploring how a shared visual vocabulary can carry a product story across discovery, learning, and creative output.</p><div class="stats"><div><b>10</b><span>AROMA PROFILES</span></div><div><b>3</b><span>CONNECTED TOOLS</span></div><div><b>1</b><span>SHARED SYSTEM</span></div></div></div><img src="{img('overview-desktop.png')}" alt="Real application overview"/></div>{footer(1)}</section>'''
html+=f'''<section class="paper"><div class="eyebrow">01 / THE DESIGN PROBLEM</div><h2>A consistent identity across<br/><em>different kinds of work.</em></h2><p class="intro">A retail menu, a teaching sheet, and a social post serve different audiences. They still need to tell a coherent story.</p><div class="columns"><article><div class="eyebrow">DISCOVER</div><h3>Retail experience</h3><p>Five category views, aroma filters, product details, staff picks, contextual learning, and an operator catalog editor.</p></article><article><div class="eyebrow">UNDERSTAND</div><h3>Education library</h3><p>Nine screen and print pieces, a terpene reference, and a preference quiz that hands the visitor into a matching menu view.</p></article><article><div class="eyebrow">EXPRESS</div><h3>Creative studio</h3><p>Six editable social formats, visual fingerprints, and chemovar cards, all using the same profile names and colors.</p></article></div>{rule}<h3>The integration decision</h3><p>Preserve the original source and working behavior. Extract shared profile identities, sample panels, and classification math. Add a clear suite navigation, connected handoffs, local persistence, and a presentation layer that makes the system easy to explore.</p><p class="caption">Source lineage: Tablet Menu v0.3 / Education Materials v1.1 / Cultivator Social Kit v1.0</p>{footer(2)}</section>'''
html+=f'''<section><div class="eyebrow">02 / THE WORKING EXPERIENCE</div><h2>One source of identity.<br/><em>Multiple useful expressions.</em></h2><div class="duo"><div><img class="shot" src="{img('menu-desktop.png')}" alt="Retail interface"/><p class="caption">RETAIL / Shared profile bands, category browsing, and a local data workflow.</p></div><div><img class="shot" src="{img('social-desktop.png')}" alt="Social creative studio"/><p class="caption">CREATIVE / Native-size exports from the actual application.</p><p>Historical examples connect the menu and creative studio. The original education and social layouts remain editable in the project.</p></div></div>{footer(3)}</section>'''
html+=f'''<section><div class="eyebrow">03 / DELIVERY & SCOPE</div><h2>A project you can explore.<br/><em>Assets you can share.</em></h2><div class="columns"><article><h3>Interactive app</h3><p>Unified navigation, reusable data modules, persistent browser catalog, CSV import/export, and source-preservation checks.</p></article><article><h3>Portfolio kit</h3><p>Real interface screenshots, native social PNGs, this four-page case study, an editable HTML version, print primer, and sharing copy.</p></article><article><h3>Reviewable source</h3><p>Three intact original files, a checksum manifest, architecture and design notes, roadmap, tests, and public repository.</p></article></div><div class="note"><h3>Evidence and boundaries</h3><p>This is a portfolio demonstration, with illustrative commercial data and historical sample panels supplied in the prototypes. Original lab PDFs and independent scientific review were not included. Educational copy needs editorial review before retail use. No live POS connection, production access control, or measured business uplift is claimed.</p></div><p style="margin-top:30px"><a href="https://flower-spectrum-suite.vercel.app">Explore: flower-spectrum-suite.vercel.app</a><br/><a href="https://github.com/cannacre8ive/flower-spectrum-suite">Source: github.com/cannacre8ive/flower-spectrum-suite</a></p>{footer(4)}</section></body></html>'''
(root/'portfolio/case-study.html').write_text(html)
print('Created editable four-page case study with embedded app screenshots.')
