import { lazy, Suspense, useEffect, useState } from 'react';
import { PROFILES } from './data/profiles.js';
import { STRAINS } from './data/strains.js';
import { bandSegments } from './lib/classifier.js';
import { CatalogProvider, useCatalog } from './lib/catalog.jsx';
import Fingerprint from './components/Fingerprint.jsx';
const TabletMenu=lazy(()=>import('./modules/TabletMenu.jsx'));
const Education=lazy(()=>import('./modules/Education.jsx'));
const routes=[['overview','Overview'],['menu','Retail menu'],['education','Education'],['social','Social studio'],['portfolio','Portfolio']];
function useRoute(){const [route,set]=useState(location.hash.slice(1)||'overview');useEffect(()=>{const f=()=>{set(location.hash.slice(1)||'overview');window.scrollTo(0,0)};window.addEventListener('hashchange',f);return()=>window.removeEventListener('hashchange',f)},[]);return route}
function Mark(){return <span className="mark-bars" aria-hidden="true">{PROFILES.slice(0,6).map(p=><i key={p.key} style={{background:p.color}}/>)}</span>}
function Overview(){const [selected,setSelected]=useState('jb');const sample=STRAINS.find(s=>s.id===selected);const [products]=useCatalog();const band=bandSegments(sample.c);return <main className="overview">
 <section className="hero"><div className="hero-copy"><div className="eyebrow">CANNACRE8IVE / FLOWER SPECTRUM SUITE</div><h1>A language for<br/>what you <em>smell.</em></h1><p className="hero-lede">From the first impression to the retail floor.<br/>One aroma system. Every touchpoint.</p><div className="hero-actions"><a className="button primary" href="#menu">Explore the retail menu <span>↗</span></a><a className="text-link" href="#portfolio">View the case study →</a></div><div className="hero-foot">RETAIL EXPERIENCE <span>·</span> EDUCATION <span>·</span> CREATIVE TOOLS</div></div>
 <div className="specimen"><div className="specimen-top"><span>AROMA SPECIMEN / 0{STRAINS.indexOf(sample)+1}</span><span className="live-dot">HISTORICAL SAMPLE</span></div><div className="specimen-graphic"><Fingerprint ranked={sample.c.ranked}/><span className="axis-label">TEN PROFILES / ONE FINGERPRINT</span></div><div className="specimen-title"><div><h2>{sample.name}</h2><p>{sample.cross}</p></div><span className="confidence">{sample.c.confidence}</span></div><div className="specimen-band">{band.map(b=><span key={b.key} style={{background:b.color,flex:b.frac}}>{b.short} {b.pct}%</span>)}</div><div className="sample-picker" aria-label="Choose sample">{STRAINS.map(s=><button key={s.id} className={selected===s.id?'active':''} onClick={()=>setSelected(s.id)}>{s.name}</button>)}</div><a className="specimen-link" href={`#social?strain=${sample.id}`}>Build assets with this sample <span>↗</span></a></div></section>
 <section className="palette-strip" aria-label="Ten aroma profiles">{PROFILES.map(p=><a href={`#menu?profile=${p.key}`} key={p.key} style={{'--profile-color':p.color}} title={`Browse ${p.label}`}><i/><span>{p.short}</span></a>)}</section>
 <section className="tools-section"><div className="section-heading"><div><div className="eyebrow">THE CONNECTED SYSTEM</div><h2>One spectrum. Three ways in.</h2></div><p>Browse it. Understand it. Put it out into the world.</p></div><div className="tool-grid">
 <a className="tool-card" href="#menu"><span className="tool-num">01 / DISCOVER</span><div className="tool-art retail-art"><div><span>FLOWER</span><b>Follow your nose.</b><i/></div><div><span>STAFF PICKS</span><b>Find a new favorite.</b><i/></div></div><h3>The retail experience <span>↗</span></h3><p>Aroma-first browsing, product details, staff picks, and a local catalog editor.</p><small>{products.length} SAMPLE PRODUCTS / 5 CATEGORIES</small></a>
 <a className="tool-card" href="#education"><span className="tool-num">02 / UNDERSTAND</span><div className="tool-art education-art"><div><small>FLOWER SPECTRUM / A FIELD PRIMER</small><strong>The nose<br/><em>knows.</em></strong><span>{PROFILES.map(p=><i key={p.key} style={{background:p.color}}/>)}</span></div></div><h3>The education library <span>↗</span></h3><p>Nine print-friendly pieces, a terpene reference, and an interactive aroma preference quiz.</p><small>9 PIECES / SCREEN + PRINT</small></a>
 <a className="tool-card" href="#social"><span className="tool-num">03 / EXPRESS</span><div className="tool-art social-art"><div><span>MEET THE FLOWER</span><strong>Jelly<br/><em>Breath.</em></strong></div><Fingerprint ranked={STRAINS[0].c.ranked} size={155}/></div><h3>The cultivator studio <span>↗</span></h3><p>Six editable social formats, aroma fingerprints, and detailed chemovar cards.</p><small>6 FORMATS / PNG EXPORT</small></a>
 </div></section>
 <section className="system-note"><div className="eyebrow">DESIGNED TO STAY CONNECTED</div><h2>The color on the menu is the<br/>color on the card.</h2><p>A shared profile library carries the same names, colors, and aroma language across the customer experience, teaching materials, and creative output.</p><a className="text-link" href="#portfolio">Explore the system design →</a></section>
 <footer className="suite-footer"><span>FLOWER SPECTRUM / CANNACRE8IVE</span><span>Portfolio demonstration · Aroma models, not effect predictions.</span></footer>
 </main>}
const downloads=[['Portfolio case study','PDF · 4 pages','flower-spectrum-case-study.pdf'],['Portfolio cover','PNG · 1600 × 1000','portfolio-cover.png'],['Social preview','PNG · 1200 × 630','social-preview.png'],['Strain highlight','PNG · 1080 × 1080','fs-highlight-jb.png'],['New drop story','PNG · 1080 × 1920','fs-drop-jb.png'],['Fingerprint ID','PNG · 1080 × 1350','fs-fingerprint-jb.png'],['Education primer','PDF · printable','education-primer.pdf'],['Complete portfolio kit','ZIP · all shareable assets','flower-spectrum-portfolio-kit.zip']];
function Portfolio(){return <main className="portfolio-page"><div className="eyebrow">SELECTED WORK / PRODUCT + BRAND SYSTEM</div><h1>From aroma data<br/>to a shared <em>language.</em></h1><p className="portfolio-intro">Flower Spectrum Suite connects a retail interface, an education library, and a creative toolkit through one visual system.</p><div className="case-meta"><div><small>DISCIPLINES</small><p>Product design · Creative direction<br/>Information design · Frontend development</p></div><div><small>DELIVERABLE</small><p>Interactive portfolio demonstration<br/>Built from three supplied prototypes</p></div><div><small>SYSTEM</small><p>10 aroma profiles · 3 connected tools<br/>9 education pieces · 6 social formats</p></div></div><img className="portfolio-preview" src="/assets/overview-desktop.png" alt="Flower Spectrum Suite overview with interactive aroma fingerprint and three connected tools"/>
 <section className="case-columns"><article><div className="eyebrow">01 / THE CHALLENGE</div><h2>A rich product story,<br/>fragmented across tools.</h2><p>Retail browsing, staff education, and cultivator marketing each need a different format. Repeating the same profile data in separate prototypes makes consistency harder to maintain.</p></article><article><div className="eyebrow">02 / THE RESPONSE</div><h2>One library.<br/>Many useful expressions.</h2><p>A shared set of profile keys, colors, and descriptions supports an integrated application. Original source files remain preserved, with a documented path from each prototype to its working module.</p></article><article><div className="eyebrow">03 / THE RESULT</div><h2>A system you can<br/>explore and take away.</h2><p>Browse the catalog, follow an aroma preference, edit the creative, and export it. The outcome is a functional demonstration with reusable assets, without invented performance metrics.</p></article></section>
 <section><div className="section-heading"><div><div className="eyebrow">THE TAKEAWAY</div><h2>A portfolio kit, ready to share.</h2></div><a className="button primary" href="/assets/flower-spectrum-portfolio-kit.zip" download>Download the full kit ↓</a></div><div className="download-grid">{downloads.map(([name,type,file])=><a key={file} href={`/assets/${file}`} download><div><strong>{name}</strong><small>{type}</small></div><span>↓</span></a>)}</div></section>
 <section className="provenance"><h2>What this demonstration represents</h2><p>The three historical sample panels and legacy educational copy come from the supplied prototypes. Original laboratory PDFs and independent scientific review were not included. Menu prices, staff attributions, and most product values are illustrative. The aroma quiz routes preferences; it does not analyze a lab report. Browser edits stay on this device. Retail compliance review, authentication, and live POS integration remain future work.</p></section><footer className="suite-footer"><a href="https://github.com/cannacre8ive/flower-spectrum-suite">Explore the source on GitHub ↗</a><a href="#overview">Back to the suite ↑</a></footer></main>}
function Shell(){const route=useRoute();const [view,query]=route.split('?');const params=new URLSearchParams(query);const active=routes.some(([id])=>id===view)?view:'overview';return <><header className="suite-header"><a className="suite-brand" href="#overview" aria-label="Flower Spectrum Suite home"><Mark/><span>Flower Spectrum<small>THE CONNECTED SUITE</small></span></a><nav aria-label="Suite navigation">{routes.map(([id,label])=><a href={`#${id}`} key={id} aria-current={active===id?'page':undefined}>{label}</a>)}</nav><a className="header-credit" href="#portfolio">CANNACRE8IVE ↗</a></header>{active!=='overview'&&active!=='portfolio'&&<div className="module-context"><span>{active==='menu'?'Retail demonstration · edits saved on this device':active==='education'?'Supplied educational content · editorial review needed before retail use':'Cultivator toolkit · historical source examples'}</span><a href="#portfolio">About this project ↗</a></div>}<Suspense fallback={<p className="loading" role="status">Opening the spectrum…</p>}>{active==='overview'?<Overview/>:active==='menu'?<TabletMenu key={route} profile={PROFILES.some(p=>p.key===params.get('profile'))?params.get('profile'):null}/>:active==='education'?<Education key={route}/>:active==='social'?<iframe key={route} className="social-frame" src={`/social.html${params.get('strain')?'?strain='+encodeURIComponent(params.get('strain')):''}`} title="Cultivator social studio"/>:<Portfolio/>}</Suspense></>}
export default function App(){return <CatalogProvider><Shell/></CatalogProvider>}
